export const ActionType = {
    SET_NAME_FIELD_VALUE: 'LOGIN_SET_NAME_FIELD_VALUE',
    SET_PASSWORD_FIELD_VALUE: 'LOGIN_SET_PASSWORD_FIELD_VALUE',
    SET_SESSION_ID_FIELD_VALUE: 'LOGIN_SET_SESSION_ID_FIELD_VALUE',
    SHOW_ERROR: 'LOGIN_SHOW_CONNECTION_ERROR',
    HIDE_ERROR: 'LOGIN_HIDE_CONNECTION_ERROR',
    SET_LOADING_MARK: 'LOGIN_SET_LOADING_MARK'
}