const SET_MESSAGE = "SET_MESSAGE";
const SET_INPUT = "SET_INPUT";
const SEND_REQUEST = "SEND_REQUEST";
const START_SENDING = "START_SENDING";
const REQUEST_ERROR = "REQUEST_ERROR";
const END_SENDING = "END_SENDING";
export const ActionType = {
    SET_MESSAGE,
    SET_INPUT,
    SEND_REQUEST,
    START_SENDING,
    REQUEST_ERROR,
    END_SENDING
};